### ISSUE TITLE
Validation per carrier: one factory, each carrier's own word

### ISSUE THREAD

**Issue by ilmeskio** [LunetteOrg/lunette#64]
Segue i carrier (#60). Assorbe anche #54 ("Validated input beyond params and body: query, header, cookie") — stessa domanda vista dal lato "quali entry sono validabili", e ora ha un caso in mano.

## Cosa è cambiato

`db0ff65` ha tolto il vocabolario dal core: non esistono più "parole" di un carrier, quindi la validazione non può più fallire "nella parola del carrier". Quello che #76/`research/with-scope-hosts` ha verificato al suo posto: uno step di validazione scrive la propria risposta nel FORMATO NATIVO dell'host (`c.json({...}, 422)` su Hono, `data({...}, {status:422})` su React Router) — non una parola condivisa, il valore che quell'host scrive comunque.

```ts
// research/with-scope-hosts/src/hono/validation.ts, la forma verificata
export const validated = <Body>(schema: ZodType<Body>) =>
  async (_app, { c, raw }, next: Next<{ body: Body }>) => {
    const result = schema.safeParse(raw)
    if (!result.success) return c.json({ error: 'invalid', issues: result.error.issues }, 422)
    return next({ body: result.data })
  }
```

## Il lavoro di questa issue

Generalizzare questo fattore: oggi produce sempre `body`, letto da `ctx.raw`. Il caso che lo motiva (segnalato in conversazione): **un header si valida con lo stesso fattore di un body** — cambia solo dove legge il valore grezzo e sotto quale chiave scrive il risultato. Due assi da decidere insieme:

- **la chiave/entry** che il fattore popola (`body`, `header`, `query`, `params`, l'`input` di tRPC…) — parametro esplicito o dedotta dal nome del verbo?
- **la promozione a verbo `.extend()`** (dalla discussione su #76): oggi è uno `.step(validated(schema))` nudo — la chiave che produce non è deducibile dalla call site senza aprire il file. Un verbo dichiarato (`.extend(bodyValidation).body(schema)`, o `.header('x-actor-id', schema)`) rende il nome della chiave visibile nel punto di chiamata, non solo nel corpo di una funzione anonima. Vedi #69 per la collisione di nomi tra estensioni che questo può sollevare.

## Cosa resta fuori

- **La lettura del valore grezzo** (`jsonBody` in questa spike) non è un blocco a sé — resta un dettaglio interno, a volte nemmeno necessario (Express ha `express.json()` a monte). Trap 18 (lettura e validazione falliscono per ragioni opposte — un fallimento di lettura genuino È un throw, un payload malformato ma arrivato È un 422) resta un vincolo da rispettare, non un'API da esporre.
- **`requireActor`**-tipo di guard NON entra qui: è #67.

## Done when

Un fattore di validazione condiviso, parametrizzato da schema e da quale entry produce, promosso a verbo `.extend()`; ogni host lo consuma e fallisce nel proprio formato nativo — dimostrato su almeno due entry diverse (es. `body` e un header) per provare che generalizza davvero.

**Comment by ilmeskio** [comment]
On the second open question — the verb's NAME — the direction is **`.validate`**,
uniform across carriers rather than `.params` on http and `.input` on trpc.

Recording what that has to reconcile, since this issue's body currently argues
the other way. §40's objection to a uniform verb was FUSION: one name that
silently meant "route params" on Hono and "the whole payload" on tRPC hides a
real difference behind a shared spelling, and that was the thing §40 removed.
§41 then removed a `validate` for a different reason — it was CARRIER-FREE, and
had to grow a core-owned `invalid` branch to have somewhere to fail.

A carrier-owned `.validate` is neither of those. The verb belongs to the carrier,
so §41 is satisfied: each fails in its own words. And §40's fusion is avoided if
the verb NAMES THE ENTRY rather than implying it:

```ts
.validate('body', schema)      // or .validate({ body: schema })
```

The entry is then explicit at the call site, and `.validate` means the same
thing everywhere — run a schema over a named entry, replace it or stop — while
which entries exist stays the carrier's business. That is what makes one name
honest rather than fused.

Which leaves the entry-naming form as the thing this issue decides: positional
(`'body'`) or a record (`{ body: schema }`). The record composes for validating
several entries at once and reads better beside the other verbs; the positional
is cheaper on inference. Neither is picked here.

Relatedly, #65 landed the gate that makes this verb necessary rather than
optional: a bare `.step` may no longer re-populate a ctx key, so narrowing
`body: unknown` to a parsed type is not expressible as a step at all. An
extension declaring its own state transformation is the way, and validation is
its first real case — the shape is pinned by a test in `verbs.test.ts`.

**Comment by ilmeskio** [comment]
## Aggiornamento dopo #60 (PR #86)

I carrier sono in, e il terreno su cui questa issue poggia è cambiato in quattro punti. Nessuno la annulla; tre le danno materiale, uno le apre una decisione che prima non aveva.

### 1. Il carrier ora dichiara COSA LO SCOPE LEGGE, e questo va risolto

Oggi la dichiarazione vive sul carrier, non sullo schema:

```ts
scope(expressCarrier<{ id: string }>())        // i params che lo scope legge
scope(honoCarrier<'/posts/:id'>())             // il pattern per cui è scritto
scope(carrier<{ id: string }>())               // tRPC: l'input che legge
scope(reactRouterCarrier<Route.LoaderArgs['params']>())
```

Serviva perché senza validazione quella è l'unica fonte del tipo. Con questa issue la fonte diventa lo schema — e allora il parametro del carrier o sparisce o diventa **una seconda verità da tenere allineata**. Decidere quale, esplicitamente, è parte del lavoro qui: è il punto in cui `__args` ha smesso di dire solo "cosa il run porta" (l'offerta dell'host) e ha cominciato a dire anche "cosa lo scope legge" (la domanda).

### 2. Il gate del pattern di rotta esiste già, e cambierà solo da dove legge

`route(pattern, scope)` su Express e Hono confronta il pattern con ciò che lo scope dichiara:

```
⛔ this route does not supply a param the scope reads: id
```

Il `PathGate` è quello di `origin/story-30/scope-impl` con le sue tre trappole ereditate (`Opaque` per il pattern illeggibile, il test invertito per la verità vacua, lo `?` dentro la chiave su Hono). Quando la fonte passa allo schema, **la forma del gate non cambia**: cambia solo `ParamsOf<S>`.

**Ma la DIREZIONE va ridecisa.** Oggi il gate è a una direzione — lo scope domanda, la rotta fornisce, un superset passa — perché confronta contro *ciò che lo scope legge*. `scope-impl` lo aveva bidirezionale perché confrontava contro *lo schema che valida*: lì un param che lo schema non dichiara è un param che nessuno controlla, ed è un buco vero. Sono due gate che sembrano lo stesso e hanno risposte diverse: con lo schema come fonte, la bidirezionalità potrebbe tornare corretta.

### 3. Su tRPC la validazione dell'input è già del framework, e già verificata

`.input(schema)` è controllato contro ciò che lo scope dichiara, **senza nessun gate nostro**: tRPC passa al resolver l'output dello schema, quindi la contravarianza rifiuta uno scope che legge ciò che lo schema non fornisce (e una procedure senza `.input()` non fornisce nulla, quindi cade nello stesso rifiuto). `.output(schema)` è controllato dall'altro lato, contro ciò che il leaf restituisce.

Quindi su tRPC il fattore generico di questa issue **non deve rifare la validazione**: deve decidere se convive con `.input()` (e per quali entry — header e `connectionParams` sono l'unico spazio che resta lì) o se su quel carrier semplicemente non serve.

### 4. La trasparenza dei mount rende il ramo 422 parte del tipo pubblico

Vincolo nuovo, e non ovvio. Ogni mount ora restituisce ciò che restituisce lo scope, perché è quello che gli host leggono: `hc<typeof app>()` su Hono, `useLoaderData<typeof loader>()` su React Router, `inferRouterOutputs` su tRPC.

Conseguenza diretta: se il verbo di validazione aggiunge il proprio ramo di fallimento all'unione dei `returns`, **quel ramo compare nel tipo che il client vede**. Un client Hono leggerà `{ id: string } | { error: string; issues: … }` e dovrà discriminare. Può essere la cosa giusta (l'errore fa parte del contratto) o rumore da nascondere — ma va scelto, perché arriva comunque.

### Cosa resta invariato

Il corpo dell'issue sopra: il fattore parametrizzato per entry, la promozione a verbo `.extend()`, la trap 18 (lettura e validazione falliscono per ragioni opposte), e il fatto che `requireActor` non entra qui ma in #67.

**Comment by ilmeskio** [comment]
### Landing on #60's ground — the carrier now answers two questions with one type

#86 shipped the four carriers and, through three rounds of review, added a gate
that makes this story's central tension concrete rather than theoretical.

**The tension.** `__args` is read TWO ways now. `Ctx` reads it as the SUPPLY —
what the run brings, what a step may annotate. The new carrier gate reads it as
the DEMAND — a mount must bring at least what the scope reads, checked by
contravariance (`ArgsGate`, §44). The two coincide only while the type comes from
the carrier, and that is a coincidence, not an invariant: the moment validation
is the source of an entry's type, they part company. Deciding which one `__args`
IS, or splitting it, is upstream of the design here — §44's *Deferred* records it
and this is the story that resolves it.

**What already exists to build on.** tRPC's carrier declares the input it reads
(`carrier<{ id: string }>()`), and `.input(schema)` is checked against it with no
gate of ours: tRPC hands a resolver the schema's OUTPUT, so contravariance
refuses a scope reading what the schema does not supply. That is the shape a
per-entry factory can aim at — a check that falls out of assignability rather
than one written.

**What a validation step will hit at the mounts.** Two gates added in #86 apply
directly:

- `StripGate` — a step may not derive a ctx key the run itself brought, on the
  mounts whose leaf strips by name. A validating step that populates `input` on
  tRPC is exactly that case: it would be dropped before `next({ ctx })` and
  silently never arrive. Refined entries need a name the carrier does not
  already occupy, or the refinement has to be an EXTENSION — which the core does
  allow, since `Refined<S, N, T>` replaces where a step may only add.
- the pattern gate reads what the scope DECLARES against what the route SUPPLIES,
  one direction. Worth knowing: on `origin/story-30/scope-impl` the same gate ran
  BOTH ways because it compared the pattern against the `.params()` SCHEMA — a
  param the schema does not declare is a param nobody validates, a real hole.
  If validation becomes the source of the params type again, the second direction
  becomes meaningful again. §45 records why.

**A doc debt this story owns.** `packages/scope/README.md` no longer describes
the input contract: the pre-#30 section (`.input`, `runScope`, the Standard
Schema paragraph) was cut in #86 rather than left contradicting the shipped API,
and replaced by a "Not here yet" pointing here. The section comes back written by
whoever settles the shape.

Conventions worth reading first: `docs/decisions.md` §44 and §45, and the new
rule in `CLAUDE.md` — a mount is tested where a step FAILS, not only where it
succeeds.

**Comment by ilmeskio** [comment]
## API proposal: one extension, three verbs, and what each argument is for

Settled with the owner in conversation, written here before any code so the
shape has a home. Not yet a decision record — that comes with the implementation.

### The shape

```ts
guard(check, onError)               // adds an entry; its name is DEDUCED
refine(name, check, onError)        // replaces an entry; its name is WRITTEN
validate(name, schema, onError)     // refine, with the check supplied by a schema
```

`guard` and `refine` are siblings over one runtime, not a chain: at runtime both
are "run the check; on failure return `onError(…)`, on success merge the result
into the ctx". The whole difference is type-level — `guard` grows `acc` the way a
step does and takes the collision gate, `refine` applies `Refined<S, N, T>`
(`Omit` plus add) and does not, because replacing is what it declares. `refine`
cannot be built on `guard`, since `guard` REFUSES to replace; it is the other
branch. `validate` is one line over `refine`.

### Why the name is deduced in one and written in the other

Adding is fully deducible: the check returns `{ actor: … }`, the verb grows `acc`
by `keyof`, and writing the name again would say nothing the type does not
already carry.

Replacing is not. A check returning `{ body: … }` when `body` exists cannot be
told apart from one that reused a name by accident — same returned object, two
very different endings (a deliberate refinement, or a second guard discarding the
first one's work). The core states exactly this for steps: "the difference
between a refinement and a collision is INTENT, which no type can read".

There is also a consistency cost to deducing everywhere: `.step(x).step(x)` is
refused today (`⛔ this ctx key is already populated`, pinned three times in
`shapes.test.ts`), so a `guard` that silently replaced would give the same
mistake two verdicts depending on which verb was used. So: **deduce where it is
safe, name where it changes something that already exists.**

### `onError` is MANDATORY, and it is what makes this carrier-free

§41 removed validation from the core because a carrier-free `validate` had
nothing to fail WITH — the core carried an `invalid` branch to give it somewhere
to land. §43 then removed the vocabulary, the other possible answer. The third
argument is the third answer, and it is neither: **the caller supplies the
failure**. The core needs no branch and no word; the verb returns whatever
`onError` produced, and from there it is an ordinary value.

It cannot be optional. The only carrier-free default is to THROW, and under §3 a
throw means infrastructure — rollback, retry, nack — while a malformed input is a
domain outcome. An optional `onError` would ship a default that lies about the
kind of the error, which is the pivot the whole library turns on. Optionality
would also re-open §41's hole from the back: with no third argument, `validate`
again has nothing to fail with.

The cost is repetition, and the cure is composition rather than a default — one
`const invalid = (issues, ctx) => …` per app, passed explicitly. That is already
this package's posture (#62: "we ship no `json`/`form` aliases, `const json =
body('json')` is one line a caller writes"). A carrier subpath MAY export a
ready-made one, still passed by name.

`onError` receives `(issues, ctx)`: it needs the ctx to answer in the host's own
door — `res.status(422).json(…)` on Express, `c.json(…, 422)` on Hono. Its return
type joins the scope's `returns` union, so **`AnswerGate` (§44) already checks it
at the mount**: an `onError` returning something the host will never send is
refused at the call site, with no new machinery.

### The one piece not yet discussed: how a check says it failed

Proposed: **a check returns a Standard Schema RESULT** — `{ value }` on success,
`{ issues }` on failure. Two things fall out of it. A schema IS then a check, so
`validate(name, schema, onError)` is `refine` with `schema['~standard'].validate`
passed in, a real specialization rather than a parallel path. And `onError`
always has something to report, instead of being handed a bare "no".

The cost is that a hand-written guard builds the wrapper:

```ts
.guard(async ({ sessions }, { req }) => {
  const actor = await sessions.of(req.header('x-actor-id'))
  return actor ? { value: { actor } } : { issues: [{ message: 'unauthorized' }] }
}, unauthorized)
```

The alternative is a sentinel for failure, which is shorter to write and leaves
`onError` with nothing to say. This is the piece to settle before implementing.

### Where it lives: ONE extension, its own subpath, not the core

`@lntt/scope/guard` — named for the general mechanism, not for its specialization.
All three verbs, added with a single `.extend()`.

**Not the core**, for three reasons in order of hardness: principle 6 forbids it
outright ("Extensions = dialects via `pipe`, never verbs grafted into the core —
inference costs weighed and rejected"); the cost is paid by every scope including
those that never call them, and this core has measured that kind of thing before
(`CtxGate` alone, reading two `keyof`s, costs +9.9% instantiations); and §46
refused two sugars in the core on the day this was designed.

**Not per carrier**, because nothing inside is host-specific — the only part that
knew about a host, how to fail, now lives in the caller.

**One extension and not two**, with the Standard Schema interface INLINED rather
than depended on. This package ships `.ts` sources with no build step, so an
unresolved import fails in the CONSUMER's build — the bug fixed in #86 by adding
`@types/express` to the peers. Splitting `validate` into its own subpath was the
alternative; inlining is better because the spec is designed to be implemented
structurally (many libraries copy it) and its version rides the property name
itself (`~standard: { version: 1 }`), so drift is visible.

Note this is not a dependency between EXTENSIONS in either case: a factory never
receives the builder (`Extension`'s own contract), so a verb cannot call another
verb. `validate` calls the refine MACHINE — a plain function — never the `refine`
VERB, and `.extend(validation)` alone would always have been enough.

**The core stays deferred, not refused**, with a trigger: if `.extend()` turns
out to be real and repeated friction in #59, where the call sites are finally
read as a whole, it reopens — and what has to be re-measured then is inference.

### What this does to §46

§46 (merged today) refused `guard`. That refusal was of a SUGAR with ONE return,
which genuinely cannot tell an enrichment from a stop without a brand — and that
part still stands. A verb with TWO FUNCTIONS dissolves the problem rather than
working around it: success and failure arrive from different places in the
signature, so there is nothing to guess. §46's own condition for reopening was "a
real case in hand", and validation is that case. The entry needs annotating, or
it reads as "guard is impossible" to whoever finds it next.

### Left open, with its cost named

`StripGate` (§44) refuses a MIDDLEWARE whose `acc` holds a key the run itself
brought, because the leaf strips the run's args by NAME. So `validate('input', …)`
passes on a tRPC `procedure` and is refused on a `middleware` — correct today,
since a refined `input` would be dropped before `next({ ctx })` exactly like an
invented one.

Uniting them is possible: strip by IDENTITY instead of by name, closing over the
values the mount actually passed, so a refined `input` survives and reaches the
context override. "Validate once in the middleware, use it in every procedure"
then becomes expressible, which is a real pattern. The cost is that the leaf must
be built PER REQUEST, undoing the mount-time hoist from #86. Worth paying only if
that pattern is wanted; otherwise today's refusal is right and costs nothing.

### What this leaves for #62

Its open question — verb or bare step factory — is answered, and not by taste:
the four read extensions ADD a key, so they are plain steps; anything that
REPLACES one must be a verb, because `CtxGate` refuses a step that re-populates.
The line falls exactly where the gate already is.

**Comment by ilmeskio** [comment]
### Settled: how a check says it failed — `fail(issues?)`, and a throw stays infrastructure

The one piece left open in the proposal above is decided.

**A check returns the addition, or `fail(issues?)`.** The brand is a symbol key
private to the module, so it cannot collide with any enrichment a check produces,
and the success path stays clean — `return { actor }`, nothing wrapped.

**This is not §43's vocabulary coming back through the side door**, and the
difference is worth stating because it looks like one. §43 removed an OPEN
ALPHABET of words, coined per carrier, checked twice. This is ONE value, owned by
one extension, meaning exactly one thing. And what §46 could not separate was an
enrichment from a HOST RESPONSE — two arbitrary values; here the host response
never passes through the check at all, since `onError` builds it. What is left for
the check to say is one bit, optionally with issues. A sentinel covers it.

**A THROW is not a failure signal, and must not be caught.** Under §3 a thrown
error is infrastructure — rollback, retry, nack. A verb that caught it and turned
it into a domain response would invert the pivot inside that one verb, and it
would catch the REAL errors too: a session repo losing its connection would be
served to the client as "invalid input". That is precisely the bug #62 already
records, "a single `catch` over both told the client its payload was malformed
when the connection had broken, hiding a 5xx behind a 4xx". To avoid it the catch
would have to discriminate on an error class of ours — a brand again, paid for
with a stack unwind and with §3 read backwards.

**`validate` adapts the schema internally**: it calls
`schema['~standard'].validate` and maps `{ issues }` onto `fail(issues)`. Three
lines inside one verb, and the payoff is that the inlined Standard Schema
interface stays an implementation detail of `validate` rather than becoming the
protocol every hand-written check has to know.

### Implementation note

#62 and #64 ship on ONE branch, closing both. The design doc's "one issue per
slice" line is deliberately set aside here, with the reason: `body` is built on
the guard machinery, so doing #62 alone would mean inventing a provisional
failure convention and rewriting it at #64 — the work done twice that the rule
exists to prevent. Two coupled slices, not a 206-file branch.
